server:
  port: 8081

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driverClassName: org.h2.Driver
